skip_tags: true

configuration: Release

cache:
  - src\packages -> **\packages.config

before_build:
  - nuget restore src\ConfigureAwait.sln

after_build:
  - src\BuildNuGetPackage\bin\Release\BuildNuGetPackage.exe artifacts

build:
  parallel: true
  project: src\ConfigureAwait.sln

test_script:
  - nunit3-console src\Tests\bin\Release\Tests.dll --x86 --result=myresults.xml;format=AppVeyor

artifacts:
  - path: artifacts\*.nupkg