configuration: Release

os: Visual Studio 2015

cache:
  - packages -> **\packages.config

before_build:
  - nuget restore src\ConfigureAwait.sln

build:
  parallel: true

artifacts:
  - path: src\ConfigureAwait\bin\Release\*.nupkg